# Generated by Django 4.2.2 on 2023-06-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bas', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
