# Generated by Django 4.2.2 on 2023-06-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bas', '0004_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='outside_review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
