# Generated by Django 4.2.2 on 2023-06-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bas', '0008_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
